### ISSUE TITLE
Using {% url %} with multi-sites

### ISSUE THREAD

**Issue by ogirardot** [wardi/django-dynamicsites-lite#1]
Hi, 
First, thank you for this lib, it works perfectly, is there any way to use "{% url %}" resolver template tag to reference from the current_site another subdomain ?

Regards, 

Olivier.

**Comment by wardi** [comment]
I think the best way to do that would be a new templatetag, {% other_site_url other_site ... %} or similar.  If you're willing to write such a thing I'd be happy to include it.

**Comment by ogirardot** [comment]
ok will look into it :)
