### ISSUE TITLE
South migration for django_site model?

### ISSUE THREAD

**Issue by elidickinson** [wardi/django-dynamicsites-lite#3]
If I run South's migrate command after adding dynamicsiteslite to my project I get this:

```
Running migrations for dynamicsiteslite:
 - Migrating forwards to 0001_convert_to_dynamic.
 > dynamicsiteslite:0001_convert_to_dynamic
[...]
ValueError: Cannot import the required field 'dynamicsites.fields.SubdomainListField'
```

If I'm following correctly, this app actually doesn't require any alterations to the Django Sites models and  migrations/0001_convert_to_dynamic.py should probably just be deleted?

**Comment by wardi** [comment]
That's correct.  The migrations should just be removed.
