### ISSUE TITLE
dynamicsites-lite unsafe with threaded WSGI

### ISSUE THREAD

**Issue by wardi** [wardi/django-dynamicsites-lite#6]
When running apache wsgi with more than one thread, very occasionally the site id doesn't get set properly.

Workaround for now is to run with separate processes instead of threads.

**Comment by bancek** [comment]
Here is a fix:

https://github.com/darkobozidar/django-dynamicsites-lite/commit/4e5b7aa7

**Comment by wardi** [comment]
@bancek looks fine to me, please go ahead and apply it.

**Comment by bancek** [comment]
This has been fixed in @45b0d05
